api:
  host: localhost
  port: 2490
  api_request_timeout: 60

log:
  app_name: sender
  level: debug
  add_trace: true
  sentry: ""
  json: false

nats:
  host: 127.0.0.1
  port: 4222

providers:
  email:
    mailgun:
      available: true
      domain: <your_mg_domain>.mailgun.org
      sender: <your_sender_address>
      private_key: <your_private_key>
      public_key: <your_public_key>
    sendgrid:
      available: false
      host: https://api.sendgrid.com
      endpoint: /v3/mail/send
      private_key: <your_private_key>
      sender: <your_sender_email>
      sender_name: <your_sender_name>
      smtp:
      available: false
      host: smtp.gmail.com
      port: 587
      from: <your_email>
      password: <your_password>
  sms:
    whatsapp:
      available: true
      api_url: https://eu1.whatsapp.chat-api.com/instance275/message?token=
      api_key: <your_account_key>
    twilio:
      available: true
      account_sid: <your_account_sid>
      auth_token: <your_auth_token>
      api_url: "https://api.twilio.com/2010-04-01/Accounts/<your_account_sid>/Messages.json"
      sender: <sender_name>
    viber:
      available: true
      api_url: http://ovh-1.ooo.ua:3039/receiveMessage

workers:
  - api-server
  - async-api-email
  - async-api-sms
